//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApp.resources.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class idiom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idiom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLApp.resources.lang.idiom", typeof(idiom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Att pic.
        /// </summary>
        internal static string TID_ATTPIC {
            get {
                return ResourceManager.GetString("TID_ATTPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change lang.
        /// </summary>
        internal static string TID_CHANGEIDIOM {
            get {
                return ResourceManager.GetString("TID_CHANGEIDIOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TID_DEL {
            get {
                return ResourceManager.GetString("TID_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit By Id.
        /// </summary>
        internal static string TID_EditById {
            get {
                return ResourceManager.GetString("TID_EditById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit content.
        /// </summary>
        internal static string TID_EditContent {
            get {
                return ResourceManager.GetString("TID_EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Private?.
        /// </summary>
        internal static string TID_ISPUBLIC {
            get {
                return ResourceManager.GetString("TID_ISPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string TID_LOGIN {
            get {
                return ResourceManager.GetString("TID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        internal static string TID_POST {
            get {
                return ResourceManager.GetString("TID_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql |.
        /// </summary>
        internal static string TID_POSTOF {
            get {
                return ResourceManager.GetString("TID_POSTOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing-Up.
        /// </summary>
        internal static string TID_REGISTER {
            get {
                return ResourceManager.GetString("TID_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Exit.
        /// </summary>
        internal static string TID_SE {
            get {
                return ResourceManager.GetString("TID_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me.
        /// </summary>
        internal static string TID_SpanClic {
            get {
                return ResourceManager.GetString("TID_SpanClic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you have an account?, login.
        /// </summary>
        internal static string TID_SpanLogin {
            get {
                return ResourceManager.GetString("TID_SpanLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t have an account yet?.
        /// </summary>
        internal static string TID_SpanRegister {
            get {
                return ResourceManager.GetString("TID_SpanRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string TID_TITLE {
            get {
                return ResourceManager.GetString("TID_TITLE", resourceCulture);
            }
        }
    }
}
